# Generated by Django 4.2.3 on 2024-08-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الحساب')),
                ('description', models.TextField(max_length=200, verbose_name='الوصف')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='رقم الحساب')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.accounttype', verbose_name='نوع الحساب')),
            ],
        ),
    ]
