# Generated by Django 4.2.3 on 2024-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'نشط'), (2, 'موقف')], default=1, verbose_name='الحالة'),
            preserve_default=False,
        ),
    ]
