# Generated by Django 4.2.3 on 2024-08-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='رمز العملة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العملة')),
                ('local', models.BooleanField(default=False, verbose_name='عملة محلية')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='رقم العملية')),
                ('date', models.DateField(verbose_name='التاريخ')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.CharField(max_length=200, verbose_name='الوصف'),
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchang_rate', models.FloatField(verbose_name='سعر التحويل')),
                ('debit', models.FloatField(blank=True, default=0, null=True, verbose_name='المبلغ المدين')),
                ('credit', models.FloatField(blank=True, default=0, null=True, verbose_name='المبلغ الدائن')),
                ('note', models.TextField(max_length=300, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.account', verbose_name='الحساب')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.currency', verbose_name='العملة')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField(verbose_name='سعر الصرف')),
                ('max_exchange_rate', models.FloatField(verbose_name='اعلى سعر صرف')),
                ('min_exchange_rate', models.FloatField(verbose_name='ادتى سعر صرف')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.currency')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ManyToManyField(to='apps.currency', verbose_name='العملات'),
        ),
    ]
